package org.eclipse.jubula.qa.api.om;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.UnsupportedEncodingException;

import org.eclipse.jubula.client.MakeR;
import org.eclipse.jubula.client.ObjectMapping;
import org.eclipse.jubula.tools.ComponentIdentifier;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class OM {
	/** the logger */
    private static Logger log = LoggerFactory.getLogger(OM.class);
    
    /** the input stream */
    private static InputStream stream;
    
    /** load input stream */
    static {
        String contentOfPropertyFile = "bound_SimpleAdder_equals_btn=rO0ABXNyAD1vcmcuZWNsaXBzZS5qdWJ1bGEudG9vbHMuaW50ZXJuYWwub2JqZWN0cy5Db21wb25lbnRJZGVudGlmaWVyAAAAAAAABAcCAAlaABRtX2VxdWFsT3JpZ2luYWxGb3VuZEQAEW1fbWF0Y2hQZXJjZW50YWdlSQAhbV9udW1iZXJPZk90aGVyTWF0Y2hpbmdDb21wb25lbnRzTAAYbV9hbHRlcm5hdGl2ZURpc3BsYXlOYW1ldAASTGphdmEvbGFuZy9TdHJpbmc7TAAUbV9jb21wb25lbnRDbGFzc05hbWVxAH4AAUwAFW1fY29tcG9uZW50UHJvcGVydGllc3QAD0xqYXZhL3V0aWwvTWFwO0wAEG1faGllcmFyY2h5TmFtZXN0ABBMamF2YS91dGlsL0xpc3Q7TAAMbV9uZWlnaGJvdXJzcQB+AANMABRtX3N1cHBvcnRlZENsYXNzTmFtZXEAfgABeHAAv/AAAAAAAAD/////cHQAE2phdmF4LnN3aW5nLkpCdXR0b25wc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAAAAZ3BAAAAAZ0AAZmcmFtZTB0ABdqYXZheC5zd2luZy5KUm9vdFBhbmVfMXQAEG51bGwubGF5ZXJlZFBhbmV0ABBudWxsLmNvbnRlbnRQYW5ldABBb3JnLmVjbGlwc2UuanVidWxhLmV4YW1wbGVzLmF1dC5hZGRlci5zd2luZy5ndWkuQ2FsY3VsYXRvclBhbmVsXzF0AAVlcXVhbHhzcQB+AAYAAAAIdwQAAAAIdAAYamF2YXguc3dpbmcuSlRleHRGaWVsZF8xdAAUamF2YXguc3dpbmcuSkxhYmVsXzF0ABRqYXZheC5zd2luZy5KTGFiZWxfMnQAGGphdmF4LnN3aW5nLkpUZXh0RmllbGRfMnQAFGphdmF4LnN3aW5nLkpMYWJlbF8zdAAYamF2YXguc3dpbmcuSlNlcGFyYXRvcl8xdAAYamF2YXguc3dpbmcuSlRleHRGaWVsZF8zdAAUamF2YXguc3dpbmcuSkxhYmVsXzR4dAAaamF2YXguc3dpbmcuQWJzdHJhY3RCdXR0b24=\nbound_SimpleAdder_inputField1_txf=rO0ABXNyAD1vcmcuZWNsaXBzZS5qdWJ1bGEudG9vbHMuaW50ZXJuYWwub2JqZWN0cy5Db21wb25lbnRJZGVudGlmaWVyAAAAAAAABAcCAAlaABRtX2VxdWFsT3JpZ2luYWxGb3VuZEQAEW1fbWF0Y2hQZXJjZW50YWdlSQAhbV9udW1iZXJPZk90aGVyTWF0Y2hpbmdDb21wb25lbnRzTAAYbV9hbHRlcm5hdGl2ZURpc3BsYXlOYW1ldAASTGphdmEvbGFuZy9TdHJpbmc7TAAUbV9jb21wb25lbnRDbGFzc05hbWVxAH4AAUwAFW1fY29tcG9uZW50UHJvcGVydGllc3QAD0xqYXZhL3V0aWwvTWFwO0wAEG1faGllcmFyY2h5TmFtZXN0ABBMamF2YS91dGlsL0xpc3Q7TAAMbV9uZWlnaGJvdXJzcQB+AANMABRtX3N1cHBvcnRlZENsYXNzTmFtZXEAfgABeHAAv/AAAAAAAAD/////cHQAFmphdmF4LnN3aW5nLkpUZXh0RmllbGRwc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAAAAZ3BAAAAAZ0AAZmcmFtZTB0ABdqYXZheC5zd2luZy5KUm9vdFBhbmVfMXQAEG51bGwubGF5ZXJlZFBhbmV0ABBudWxsLmNvbnRlbnRQYW5ldABBb3JnLmVjbGlwc2UuanVidWxhLmV4YW1wbGVzLmF1dC5hZGRlci5zd2luZy5ndWkuQ2FsY3VsYXRvclBhbmVsXzF0AAZ2YWx1ZTF4c3EAfgAGAAAACHcEAAAACHQAFGphdmF4LnN3aW5nLkpMYWJlbF8xdAAUamF2YXguc3dpbmcuSkxhYmVsXzJ0ABhqYXZheC5zd2luZy5KVGV4dEZpZWxkXzF0ABRqYXZheC5zd2luZy5KTGFiZWxfM3QAGGphdmF4LnN3aW5nLkpTZXBhcmF0b3JfMXQAGGphdmF4LnN3aW5nLkpUZXh0RmllbGRfMnQAFGphdmF4LnN3aW5nLkpMYWJlbF80dAAVamF2YXguc3dpbmcuSkJ1dHRvbl8xeHQAH2phdmF4LnN3aW5nLnRleHQuSlRleHRDb21wb25lbnQ=\nbound_SimpleAdder_inputField2_txf=rO0ABXNyAD1vcmcuZWNsaXBzZS5qdWJ1bGEudG9vbHMuaW50ZXJuYWwub2JqZWN0cy5Db21wb25lbnRJZGVudGlmaWVyAAAAAAAABAcCAAlaABRtX2VxdWFsT3JpZ2luYWxGb3VuZEQAEW1fbWF0Y2hQZXJjZW50YWdlSQAhbV9udW1iZXJPZk90aGVyTWF0Y2hpbmdDb21wb25lbnRzTAAYbV9hbHRlcm5hdGl2ZURpc3BsYXlOYW1ldAASTGphdmEvbGFuZy9TdHJpbmc7TAAUbV9jb21wb25lbnRDbGFzc05hbWVxAH4AAUwAFW1fY29tcG9uZW50UHJvcGVydGllc3QAD0xqYXZhL3V0aWwvTWFwO0wAEG1faGllcmFyY2h5TmFtZXN0ABBMamF2YS91dGlsL0xpc3Q7TAAMbV9uZWlnaGJvdXJzcQB+AANMABRtX3N1cHBvcnRlZENsYXNzTmFtZXEAfgABeHAAv/AAAAAAAAD/////cHQAFmphdmF4LnN3aW5nLkpUZXh0RmllbGRwc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAAAAZ3BAAAAAZ0AAZmcmFtZTB0ABdqYXZheC5zd2luZy5KUm9vdFBhbmVfMXQAEG51bGwubGF5ZXJlZFBhbmV0ABBudWxsLmNvbnRlbnRQYW5ldABBb3JnLmVjbGlwc2UuanVidWxhLmV4YW1wbGVzLmF1dC5hZGRlci5zd2luZy5ndWkuQ2FsY3VsYXRvclBhbmVsXzF0AAZ2YWx1ZTJ4c3EAfgAGAAAACHcEAAAACHQAGGphdmF4LnN3aW5nLkpUZXh0RmllbGRfMXQAFGphdmF4LnN3aW5nLkpMYWJlbF8xdAAUamF2YXguc3dpbmcuSkxhYmVsXzJ0ABRqYXZheC5zd2luZy5KTGFiZWxfM3QAGGphdmF4LnN3aW5nLkpTZXBhcmF0b3JfMXQAGGphdmF4LnN3aW5nLkpUZXh0RmllbGRfMnQAFGphdmF4LnN3aW5nLkpMYWJlbF80dAAVamF2YXguc3dpbmcuSkJ1dHRvbl8xeHQAH2phdmF4LnN3aW5nLnRleHQuSlRleHRDb21wb25lbnQ=\nbound_SimpleAdder_resultField_txf=rO0ABXNyAD1vcmcuZWNsaXBzZS5qdWJ1bGEudG9vbHMuaW50ZXJuYWwub2JqZWN0cy5Db21wb25lbnRJZGVudGlmaWVyAAAAAAAABAcCAAlaABRtX2VxdWFsT3JpZ2luYWxGb3VuZEQAEW1fbWF0Y2hQZXJjZW50YWdlSQAhbV9udW1iZXJPZk90aGVyTWF0Y2hpbmdDb21wb25lbnRzTAAYbV9hbHRlcm5hdGl2ZURpc3BsYXlOYW1ldAASTGphdmEvbGFuZy9TdHJpbmc7TAAUbV9jb21wb25lbnRDbGFzc05hbWVxAH4AAUwAFW1fY29tcG9uZW50UHJvcGVydGllc3QAD0xqYXZhL3V0aWwvTWFwO0wAEG1faGllcmFyY2h5TmFtZXN0ABBMamF2YS91dGlsL0xpc3Q7TAAMbV9uZWlnaGJvdXJzcQB+AANMABRtX3N1cHBvcnRlZENsYXNzTmFtZXEAfgABeHAAv/AAAAAAAAD/////cHQAFmphdmF4LnN3aW5nLkpUZXh0RmllbGRwc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAAAAZ3BAAAAAZ0AAZmcmFtZTB0ABdqYXZheC5zd2luZy5KUm9vdFBhbmVfMXQAEG51bGwubGF5ZXJlZFBhbmV0ABBudWxsLmNvbnRlbnRQYW5ldABBb3JnLmVjbGlwc2UuanVidWxhLmV4YW1wbGVzLmF1dC5hZGRlci5zd2luZy5ndWkuQ2FsY3VsYXRvclBhbmVsXzF0AANzdW14c3EAfgAGAAAACHcEAAAACHQAGGphdmF4LnN3aW5nLkpUZXh0RmllbGRfMXQAFGphdmF4LnN3aW5nLkpMYWJlbF8xdAAUamF2YXguc3dpbmcuSkxhYmVsXzJ0ABhqYXZheC5zd2luZy5KVGV4dEZpZWxkXzJ0ABRqYXZheC5zd2luZy5KTGFiZWxfM3QAGGphdmF4LnN3aW5nLkpTZXBhcmF0b3JfMXQAFGphdmF4LnN3aW5nLkpMYWJlbF80dAAVamF2YXguc3dpbmcuSkJ1dHRvbl8xeHQAH2phdmF4LnN3aW5nLnRleHQuSlRleHRDb21wb25lbnQ=\n"; //$NON-NLS-1$
        try {
            stream = new ByteArrayInputStream(
                    contentOfPropertyFile.getBytes("ISO-8859-1")); //$NON-NLS-1$
        } catch (UnsupportedEncodingException e) {
            log.error(e.getLocalizedMessage(), e);
        }
    }
    
    /** the object mapping */
    private static ObjectMapping objectMapping = MakeR.createObjectMapping(stream);
    
    /** The component identifier for "bound_SimpleAdder_resultField_txf"*/
    public static final ComponentIdentifier bound_SimpleAdder_resultField_txf = objectMapping.get("bound_SimpleAdder_resultField_txf"); //$NON-NLS-1$
    /** The component identifier for "bound_SimpleAdder_inputField1_txf"*/
    public static final ComponentIdentifier bound_SimpleAdder_inputField1_txf = objectMapping.get("bound_SimpleAdder_inputField1_txf"); //$NON-NLS-1$
    /** The component identifier for "bound_SimpleAdder_equals_btn"*/
    public static final ComponentIdentifier bound_SimpleAdder_equals_btn = objectMapping.get("bound_SimpleAdder_equals_btn"); //$NON-NLS-1$
    /** The component identifier for "bound_SimpleAdder_inputField2_txf"*/
    public static final ComponentIdentifier bound_SimpleAdder_inputField2_txf = objectMapping.get("bound_SimpleAdder_inputField2_txf"); //$NON-NLS-1$
    
    private OM() {
        // private
    }
}
