<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jubula"
    nsURI="http://jubula/1.0" nsPrefix="jubula">
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true" eSuperTypes="#//Timestamp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="NodeList" upperBound="-1"
        eType="#//Node" containment="true" eOpposite="#//Node/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Node"
        eOpposite="#//Node/NodeList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Guid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ParentProjectId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Timestamp" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Generated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Active" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Timestamp" abstract="true" interface="true"
      eSuperTypes="#//PersistentObject">
    <eOperations name="setTimestamp">
      <eParameters name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
    <eOperations name="getTimestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersistentObject" abstract="true" interface="true">
    <eOperations name="getVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eOperations name="getId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getParentProjectId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eOperations name="setParentProjectId">
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParamNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="RefTestSuite" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestSuite" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestJob" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cap" eSuperTypes="#//ParamNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="#//ParamNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase" eSuperTypes="#//ParamNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecTestCase" eSuperTypes="#//TestCase"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpecTestCase" eSuperTypes="#//TestCase"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMapping" eSuperTypes="#//Timestamp"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractGUIDName" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentName" eSuperTypes="#//AbstractGUIDName"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParamName" eSuperTypes="#//AbstractGUIDName"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectName" eSuperTypes="#//AbstractGUIDName"/>
  <eClassifiers xsi:type="ecore:EClass" name="AUTConfig" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="AUTCont" eSuperTypes="#//PersistentObject #//Wrapper"/>
  <eClassifiers xsi:type="ecore:EClass" name="AUTMain" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="CheckConfCont" eSuperTypes="#//PersistentObject #//Wrapper"/>
  <eClassifiers xsi:type="ecore:EClass" name="CheckConf" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompIdentifier" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompNamesPair" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataSet" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecObjCont" eSuperTypes="#//PersistentObject #//Wrapper"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMappingAssoziation" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMappingCategory" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMappingProfile" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParamDescription" abstract="true" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="CapParamDescription" eSuperTypes="#//ParamDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="TcParamDescription" eSuperTypes="#//ParamDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="Wrapper" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpecObjCont" eSuperTypes="#//Wrapper"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectProperties" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReusedProject" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestData" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestDataCategory" eSuperTypes="#//TestDataNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestDataCube" eSuperTypes="#//TestDataNode #//ModifiableParameterInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="UsedToolkit" eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestDataNode" abstract="true" interface="true"
      eSuperTypes="#//PersistentObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModifiableParameterInterface" abstract="true"
      interface="true"/>
</ecore:EPackage>
