#!/bin/ksh
#set -x

if [ $# -ne 1 ]
then
    echo 
    echo "usage: $0 <directory>"
    echo 
    echo "All files with the extension .PSD are converted to both .JPG and .EPS files."
    echo 
    exit 1
fi

cd $1

if [ ! -f *.psd ]; then exit 0; fi

for i in `ls *.psd`
do
  bfile=`basename $i .psd`

  if [ ${bfile}.psd -nt ${bfile}.jpg  -o  ${bfile}.psd -nt ${bfile}.eps  ]
  then 
     
      echo "Please convert $i to both JPEG and EPS"
      echo ""
      exit 1

    echo Converting $i...  
    rm -f ${bfile}.jpg  ${bfile}.eps ${bfile}.pdf
    convert "${bfile}.psd" -flatten "${bfile}.jpg"	
    convert "${bfile}.psd" -flatten "${bfile}.eps"
  fi
done
